function(static_lib_file_ending STATIC_LIB_FILE_ENDING)
    set(STATIC_LIB_FILE_ENDING "" PARENT_SCOPE)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(STATIC_LIB_FILE_ENDING "a" PARENT_SCOPE)
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        set(STATIC_LIB_FILE_ENDING "lib" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "No supported compiler detected" )
    endif()
endfunction()

function(dynamic_lib_file_ending DYNAMIC_LIB_FILE_ENDING)
    set(DYNAMIC_LIB_FILE_ENDING "" PARENT_SCOPE)
    if (WIN32)
        set(DYNAMIC_LIB_FILE_ENDING "dll" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "No supported OS" )
    endif()
endfunction()